version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start
    restart: unless-stopped
    ports:
      - "8180:8080"
    networks:
      - keycloak-net
    depends_on:
      - postgres
    environment:
      # --- Cấu hình Database ---
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD} 
      - KC_DB_SCHEMA=public

      # --- Cấu hình Admin ---
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER} 
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD} 

      # --- Cấu hình Reverse Proxy ---
      - KC_PROXY=edge
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
      - KC_HTTP_ENABLED=true

  postgres:
    image: postgres:15
    container_name: keycloak_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-net
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 

volumes:
  postgres_data:
    driver: local

networks:
  keycloak-net:
    driver: bridge